;Key values returned from Kernal function GETIN
    KEYVAL_ESC = $1b
    KEYVAL_ENTER = $0d
    KEYVAL_BACKSPACE = $14
    KEYVAL_TAB = $09
    KEYVAL_LEFT = $9d
    KEYVAL_RIGHT = $1d
    KEYVAL_UP = $91
    KEYVAL_DOWN = $11
    KEYVAL_HOME = $13
    KEYVAL_SHIFT_HOME = $93
    KEYVAL_F1 = $85
    KEYVAL_F2 = $89
    KEYVAL_F3 = $86
    KEYVAL_F4 = $8a
    KEYVAL_F5 = $87
    KEYVAL_F6 = $8b
    KEYVAL_F7 = $88
    KEYVAL_F8 = $8c
    KEYVAL_A = $41
    KEYVAL_N = $4e
    KEYVAL_T = $54
    KEYVAL_Y = $59
    KEYVAL_V = $56
    KEYVAL_SPACE = $20
    KEYVAL_SHIFT_SPACE = $a0

;Numerical keypad
    KEYVAL_0 = 48
    KEYVAL_1 = 49
    KEYVAL_2 = 50
    KEYVAL_3 = 51
    KEYVAL_4 = 52
    KEYVAL_5 = 53
    KEYVAL_6 = 54
    KEYVAL_7 = 55
    KEYVAL_8 = 56
    KEYVAL_9 = 57
    KEYVAL_DP = 46
    KEYVAL_DIV = 47
    KEYVAL_MUL = 42
    KEYVAL_SUB = 45
    KEYVAL_ADD = 43
    KEYVAL_EQUAL = 61

;Key values returned from custom scancode handler
    KEYVAL_DELETE = $15
    KEYVAL_END = $16
    KEYVAL_PGUP = $17
    KEYVAL_PGDN = $18
    KEYVAL_INSERT = $1a